/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgDocument = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path fill="currentColor" d="M18.475 3.6L24.4 9.571V28.4H7.6V3.6h10.875zM19.974 0H4v32h24V8.088L19.974 0z" />
  </svg>
))
export default SvgDocument
