/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgAnchorDown = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M13.687 24.004V0h4.474v24.156l8.495-8.495 2.842 2.842L16 32.001 2.501 18.502l2.842-2.842 8.344 8.344z"
    />
  </svg>
))
export default SvgAnchorDown
