/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgAnchorTop = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M13.687 7.996V32h4.474V7.844l8.495 8.495 2.842-2.842L16-.001 2.501 13.498l2.842 2.842 8.344-8.344z"
    />
  </svg>
))
export default SvgAnchorTop
