/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgBurgerMenu = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M1.846 23.692h28.308a1.846 1.846 0 0 1 0 3.692H1.846a1.846 1.846 0 0 1 0-3.692zm0-9.846h28.308a1.846 1.846 0 0 1 0 3.692H1.846a1.846 1.846 0 0 1 0-3.692zm0-9.846h28.308a1.846 1.846 0 0 1 0 3.692H1.846a1.846 1.846 0 0 1 0-3.692z"
    />
  </svg>
))
export default SvgBurgerMenu
