/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgCheckboxInactive = React.forwardRef(
  (props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
    <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
      <path
        fill="currentColor"
        d="M2 3.414v24.728l12.364-12.364L2 3.414zM2.971 30h25.615L15.778 17.192 2.97 30zM30 28.586V2.971L17.192 15.779 30 28.587zM28.142 2H3.414l12.364 12.364L28.142 2zM30.137.005L30.142 0l.005.005A2 2 0 0 1 31.999 2v28a2 2 0 0 1-2 2h-28a2 2 0 0 1-1.995-1.852l-.005-.005.005-.005a2.065 2.065 0 0 1-.005-.137v-28c0-.179.024-.353.068-.518l-.068-.068.133-.133A2.01 2.01 0 0 1 1.28.134l.133-.133.068.068a2.01 2.01 0 0 1 .518-.068h28c.046 0 .092.002.137.005z"
      />
    </svg>
  )
)
export default SvgCheckboxInactive
