/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgCheckboxFill = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M2 0h28a2 2 0 0 1 2 2v28a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2zm14.3 26.477a2.401 2.401 0 0 0 2.122-1.281l9.301-17.681a2.398 2.398 0 1 0-4.243-2.231l-7.928 15.072-7.629-6.295a2.396 2.396 0 1 0-3.051 3.697l9.902 8.173c.433.358.975.548 1.526.548z"
    />
  </svg>
))
export default SvgCheckboxFill
