/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgClear = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path d="M16 32C7.163 32 0 24.837 0 16S7.163 0 16 0s16 7.163 16 16-7.163 16-16 16zm4.978-22.4L16 14.578 11.023 9.6l-1.422 1.422L14.578 16l-4.977 4.978 1.422 1.422L16 17.422l4.978 4.978 1.422-1.422L17.422 16l4.978-4.978L20.978 9.6z" />
  </svg>
))
export default SvgClear
