/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgClose = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path fill="currentColor" d="M20 16l12 12-4 4-12-12L4 32l-4-4 12-12L0 4l4-4 12 12L28 0l4 4-12 12z" />
  </svg>
))
export default SvgClose
