/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgFavouriteFollowing = React.forwardRef(
  (props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
    <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
      <path
        fill="currentColor"
        d="M8 0v32l8.333-6.666L24.666 32V0H8zm5.499 10.114l-2.932-2.76 3.975-.648 1.719-3.642 1.845 3.58 3.995.509-2.834 2.861.75 3.956-3.596-1.812-3.531 1.936.611-3.98z"
      />
    </svg>
  )
)
export default SvgFavouriteFollowing
