/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgLeftArrow = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M7.996 18.313H32v-4.474H7.844l8.495-8.495-2.842-2.842L-.001 16l13.499 13.499 2.842-2.842-8.344-8.344z"
    />
  </svg>
))
export default SvgLeftArrow
