/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgMail = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M3 8.118V25h26V8.118L18.377 17.95a3.5 3.5 0 0 1-4.755 0L2.999 8.118zM25.792 7H6.208l9.452 8.749a.5.5 0 0 0 .679 0L25.791 7zM2 4h28a2 2 0 0 1 2 2v20a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2z"
    />
  </svg>
))
export default SvgMail
