/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgMinus = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M16 32C7.163 32 0 24.837 0 16S7.163 0 16 0s16 7.163 16 16-7.163 16-16 16zM6 14v4h20v-4H6z"
    />
  </svg>
))
export default SvgMinus
