/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgMore = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M3.81 19.619a3.81 3.81 0 1 1 0-7.62 3.81 3.81 0 0 1 0 7.62zm12.19 0a3.81 3.81 0 1 1 0-7.62 3.81 3.81 0 0 1 0 7.62zm12.19 0a3.81 3.81 0 1 1 0-7.62 3.81 3.81 0 0 1 0 7.62z"
    />
  </svg>
))
export default SvgMore
