/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgMove = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M26.2 12.388L16 3.716 5.8 12.388 4 10.323 16-.001l12 10.324-1.8 2.065zm0 7.259l1.8 2.065-12 10.324L4 21.712l1.8-2.065L16 28.319l10.2-8.672z"
    />
  </svg>
))
export default SvgMove
