/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgRadioButtonFill = React.forwardRef(
  (props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
    <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
      <path
        fill="currentColor"
        d="M16 30c7.732 0 14-6.268 14-14S23.732 2 16 2 2 8.268 2 16s6.268 14 14 14zm0 2C7.163 32 0 24.837 0 16S7.163 0 16 0s16 7.163 16 16-7.163 16-16 16zm0-6c-5.523 0-10-4.477-10-10S10.477 6 16 6s10 4.477 10 10-4.477 10-10 10z"
      />
    </svg>
  )
)
export default SvgRadioButtonFill
