/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgRightArrow = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M24.004 13.687H0v4.474h24.156l-8.495 8.495 2.842 2.842L32.001 16 18.502 2.501 15.66 5.343l8.344 8.344z"
    />
  </svg>
))
export default SvgRightArrow
