/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgSliderOn = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M9.6 26C4.298 26 0 21.523 0 16S4.298 6 9.6 6h12.8c5.302 0 9.6 4.477 9.6 10s-4.298 10-9.6 10H9.6z"
    />
    <path fill="inherit" d="M30.002 16a8 8 0 0 1-8 8 8 8 0 1 1 8-8z" />
  </svg>
))
export default SvgSliderOn
