/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgUp = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path fill="currentColor" d="M29.602 24.518l-13.6-11.562-13.6 11.562-2.4-2.752 16-13.764 16 13.764z" />
  </svg>
))
export default SvgUp
