/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgBrazil = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 40 32" ref={svgRef} {...props}>
    <path fill="#68bd45" d="M0 32h40V0H0z" />
    <path fill="#2d2926" opacity={0.15} d="M38 30H2V2h36v28zm2-30H0v32h40V0z" />
    <path fill="#fcd21d" d="M3.078 16.684L20 4.336l16.69 12.348L20 29.226z" />
    <path fill="#1b5786" d="M28.8 16.8a8.8 8.8 0 1 1-17.6 0 8.8 8.8 0 0 1 17.6 0z" />
    <path
      fill="#fff"
      d="M12.154 12.811c6.431.155 12.256 1.866 16.627 4.577-.033.501-.108.99-.221 1.464-4.487-2.718-10.46-4.396-17.029-4.451a8.75 8.75 0 0 1 .623-1.59z"
    />
  </svg>
))
export default SvgBrazil
