/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgFrance = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 40 32" ref={svgRef} {...props}>
    <path fill="#fff" d="M0 32h40V0H0z" />
    <path fill="#be1e2d" d="M26.4 32H40V0H26.4z" />
    <path fill="#002b45" d="M0 32h13.6V0H0z" />
    <path fill="#2d2926" opacity={0.15} d="M38 30H2V2h36v28zm2-30H0v32h40V0z" />
  </svg>
))
export default SvgFrance
