/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgJapan = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 40 32" ref={svgRef} {...props}>
    <path fill="#fff" d="M0 32h40V0H0z" />
    <path fill="#2d2926" opacity={0.15} d="M38 30H2V2h36v28zm2-30H0v32h40V0z" />
    <path fill="#be1e2d" d="M28.8 16.8a8.8 8.8 0 1 1-17.6 0 8.8 8.8 0 0 1 17.6 0z" />
  </svg>
))
export default SvgJapan
