/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgSlovenia = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 40 32" ref={svgRef} {...props}>
    <path fill="#1b5786" d="M0 32h40V0H0z" />
    <path fill="#be1e2d" d="M0 32h40V21.6H0z" />
    <path fill="#fff" d="M0 10.4h40V0H0z" />
    <path fill="#2d2926" opacity={0.15} d="M38 30H2V2h36v28zm2-30H0v32h40V0z" />
    <path
      fill="#1b5786"
      d="M15.894 11.28c0 2.18-2.666 4.586-3.948 4.586C10.88 15.866 8 13.46 8 11.28V6.586C8 5.822 9.768 5.2 11.946 5.2c2.18 0 3.948.622 3.948 1.386v4.694z"
    />
    <path
      fill="#fff"
      d="M14.965 11.292c0 1.668-2.04 3.508-3.018 3.508-.816 0-3.018-1.84-3.018-3.508l1.224-1.754c0-.29.61.776.61.776l1.184-2.448 1.264 2.448.612-.612 1.142 1.59z"
    />
    <path
      fill="none"
      stroke="#be1e2d"
      strokeLinejoin="miter"
      strokeLinecap="butt"
      strokeMiterlimit={4}
      strokeWidth={0.8}
      d="M8.106 10.235v1.044c0 2.18 2.88 4.586 3.948 4.586 1.278 0 3.946-2.406 3.946-4.586v-1.086"
    />
    <path
      fill="#fcd21d"
      d="M11.971 7.36l-.466.268.09-.53-.378-.358.52-.098.234-.49.232.47.522.054-.378.39.09.52-.466-.226zm1.599 0l-.466.268.09-.53-.378-.358.52-.098.234-.49.234.47.52.054-.378.39.09.52-.466-.226zm-3.2 0l-.466.268.09-.53-.378-.358.522-.098.232-.49.234.47.52.054-.376.39.088.52-.466-.226z"
    />
  </svg>
))
export default SvgSlovenia
