/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgArrivalsFerry = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M17.617 13.134c4.166.497 10.821 4.74 10.821 8.02l-2.688 8.651c-1.24.398-1.62 1.742-3.237 1.742-1.785 0-3.721-1.639-5.497-1.832l.601-16.581zM5.01 21.154c0-3.28 6.655-7.522 10.821-8.02l.601 16.582c-1.777.192-3.713 1.832-5.498 1.832-1.617 0-1.996-1.345-3.236-1.742L5.01 21.155zm3.869-10.662h15.997a8.693 8.693 0 0 1-.044-.095c-.779-1.651-1.348-1.616-5.537-1.616H14.46c-4.189 0-4.758-.034-5.537 1.616l-.044.095zm10.396-4.403h10.532l-.936 3.013h-2.278l1.641 9.74c-1.227-1.672-3.33-3.991-5.531-5.256 2.647-.113 3.161-.516 2.673-1.92H8.379c-.471 1.355-.008 1.778 2.406 1.908-2.496 1.42-4.578 4.088-5.496 6.039L7.213 9.102H4.935l-.936-3.013H14.53L16.126 0h1.551l1.596 6.089z"
    />
  </svg>
))
export default SvgArrivalsFerry
