/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgCalendarOutbound = React.forwardRef(
  (props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
    <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
      <path
        fill="currentColor"
        d="M26.98 4.65H23.5v-.9a.75.75 0 0 0-1.5 0v.9H10v-.9a.75.75 0 0 0-1.5 0v.9H5.02A1.039 1.039 0 0 0 4 5.7v21.765A1.016 1.016 0 0 0 5.02 28.5h21.96A1.018 1.018 0 0 0 28 27.465V5.7a1.033 1.033 0 0 0-1.02-1.05zM26.5 27h-21V6.15h3v.57a.75.75 0 0 0 1.5 0v-.57h12v.57a.75.75 0 0 0 1.5 0v-.57h3V27zM8 14a1 1 0 0 0-1 1v1.18a1 1 0 0 0 1 1h1.195a1 1 0 0 0 1-1V15a1 1 0 0 0-1-1H8zm0-5a1 1 0 0 0-1 1v1.18a1 1 0 0 0 1 1h1.195a1 1 0 0 0 1-1V10a1 1 0 0 0-1-1H8zm5 5a1 1 0 0 0-1 1v1.18a1 1 0 0 0 1 1h1.195a1 1 0 0 0 1-1V15a1 1 0 0 0-1-1H13zm0-5a1 1 0 0 0-1 1v1.18a1 1 0 0 0 1 1h1.195a1 1 0 0 0 1-1V10a1 1 0 0 0-1-1H13zm5 5a1 1 0 0 0-1 1v1.18a1 1 0 0 0 1 1h1.195a1 1 0 0 0 1-1V15a1 1 0 0 0-1-1H18zm0-5a1 1 0 0 0-1 1v1.18a1 1 0 0 0 1 1h1.195a1 1 0 0 0 1-1V10a1 1 0 0 0-1-1H18zm5 5a1 1 0 0 0-1 1v1.18a1 1 0 0 0 1 1h1.195a1 1 0 0 0 1-1V15a1 1 0 0 0-1-1H23zm0-5a1 1 0 0 0-1 1v1.18a1 1 0 0 0 1 1h1.195a1 1 0 0 0 1-1V10a1 1 0 0 0-1-1H23z"
      />
      <path fill="inherit" d="M16.495 18l-1.17 1.17 1.905 1.89h-5.175v1.665h5.355l-2.1 2.13 1.2 1.155 3.99-4.05z" />
    </svg>
  )
)
export default SvgCalendarOutbound
