/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as React from 'react'
const SvgTrailer = React.forwardRef((props: React.SVGProps<SVGSVGElement>, svgRef: React.Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M31.084 18.887v2.13H15.878v-.43a3.917 3.917 0 0 0-7.824 0v.43H2.438a2.117 2.117 0 0 1-2.13-2.129v-4.245c5.477-.079 19.213-.079 25.069-.079l-.077 3.728a.867.867 0 0 1 .077.596h5.705zm-19.167-1.104a2.745 2.745 0 0 1 2.77 2.759 2.76 2.76 0 1 1-2.769-2.758zm0 4.194a1.434 1.434 0 1 0 .024-2.87 1.434 1.434 0 0 0-.025 2.871zM4.207 9h16.966a2 2 0 0 1 2 2v2.414H2.207V11a2 2 0 0 1 2-2z"
    />
  </svg>
))
export default SvgTrailer
